---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-collection-tree
  labels:
    env: dev
    app: data-collection-tree
spec:
  replicas: 1
  selector:
    matchLabels:
      env: dev
      app: data-collection-tree
  template:
    metadata:
      labels:
        env: dev
        app: data-collection-tree
    spec:
      containers:
        - image: skp123/data_collection_tree:0.1
          imagePullPolicy: IfNotPresent
          name: data-collection-tree
          ports:
            - containerPort: 8080
              name: tree-api
              protocol: TCP
          resources:
            requests:
              cpu: 20m
              memory: 55M

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: data-collection-tree
  name: data-collection-tree
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    env: dev
    app: data-collection-tree
  type: ClusterIP

